platform :ios, '11.0'
use_frameworks!

target 'Toolbelt_Example' do
  pod 'Toolbelt', :path => '../'
  pod 'ToolbeltUI', :path => '../'
  
  pod 'SnapKit'
  pod 'Hue'

  target 'Toolbelt_Tests' do
    inherit! :search_paths

    
  end
end
